name: package-linters

on:
  pull_request:
    branches: ["main", "develop"]


jobs:

  code_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install .
      - name: Set all paths to be checked
        run: echo "paths=src unittests" >> $GITHUB_ENV
      - name: Run linters
        run: |
          ruff check ${{ env.paths }}
